### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "teste008@iel.com",
    "password": "123458abc#",
    "bogus": "bogus"
}

### SignIn
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "teste005@iel.com",
    "password": "123456abc#"
}

### Sign in with an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "teste007@iel.com",
    "password": "123457abc#"
}

### Set a color in session
GET http://localhost:3000/auth/colors/red

### Get a color from session
GET http://localhost:3000/auth/colors



### Find a user by id
GET http://localhost:3000/auth/1

### Find users by email
GET http://localhost:3000/auth/?email=gez@iel.com

### Delete a user by id
DELETE http://localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "teste0003@iel.com",
    "bogus": "bogus"
}